### ISSUE TITLE
Raise Mountain - Exception error

### ISSUE THREAD

**Issue by JustJinxed** [Xilef11/Runes-of-Wizardry#35]
Got this while attempting to use the raise mountain rune. The outside of the clay square, didn't have surrounding dirt, and I was trying it on a modded block type. Not sure which might have caused it, or if either did. 

Full crashlog: [https://pastebin.com/5SpjrHpV](url)

`
[17:16:19] [Server thread/INFO] [runesofwizardry]: Finished finding dust pattern. Found 13 blocks in 33 calls
[17:16:19] [Server thread/INFO] [runesofwizardry]: Converting to array: there are 5 horizontal blocks and 3 vertical blocks. NW corner is BlockPos{x=-750, y=69, z=626} and SE corner is BlockPos{x=-746, y=69, z=628}
[17:16:19] [Server thread/INFO] [runesofwizardry]: Found sacrifice: [1xtile.flower2@0]
[17:16:19] [Server thread/INFO] [runesofwizardry]: Comparing sacrifices: [1xtile.flower2@0] and [1xtile.flower2@0]
[17:16:19] [Server thread/INFO] [runesofwizardry]: Top-left block is :BlockPos{x=-750, y=69, z=626} and entity Pos is: BlockPos{x=-748, y=69, z=627}
[17:16:19] [Server thread/INFO] [runesofwizardry]: Formed Rune: runesofwizardry_classics.rune.mountain facing north by <PROFILE NAME>
[17:16:19] [Server thread/INFO] [runesofwizardry_classics]: Found Edge: x: -754 to -743 z: 621 to 631 total blocks: 42
[17:16:19] [Server thread/INFO] [runesofwizardry_classics]: Found 132 blocks in area
[17:16:23] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) ~[cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at com.zpig333.runesofwizardry.tileentity.TileEntityDustActive.func_189515_b(TileEntityDustActive.java:202) ~[TileEntityDustActive.class:?]
	at com.zpig333.runesofwizardry.tileentity.TileEntityDustPlaced.func_189517_E_(TileEntityDustPlaced.java:408) ~[TileEntityDustPlaced.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52) ~[gw.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:254) ~[mb.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115) ~[mc.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221) ~[lw.class:?]
	at WorldServerOF.func_72835_b(WorldServerOF.java:37) ~[WorldServerOF.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	... 4 more
`

**Comment by JustJinxed** [comment]
Upon re-entry, same error and client crash. Seems the dust is still trying to tick / world unrecoverable without removal of mod/block through MCedit or reload without mod.

**Comment by Xilef11** [comment]
Hello and sorry for the delay, somehow I don't get email notifications anymore :/

Was this on a single-player world or a server? If server, does it also happen in single-player? Anything special about the blocks it was trying to lift (and does it work with other blocks?)

In the future, if you don't want to mess with MCedit or lose other blocks/items from the mod, there is an opption in forge.cfg to remove erroring tileentities, turning it on may help (but remember to turn it off afterwards)

**Comment by Xilef11** [comment]
Fixed in version 0.8.2 for MC 1.11.2
