### ISSUE TITLE
JEI Buildcraft Facades Crash

### ISSUE THREAD

**Issue by liquidblur** [Xilef11/Runes-of-Wizardry#44]
java.lang.ArrayIndexOutOfBoundsException: 4
	at xilef11.mc.runesofwizardry_classics.items.EnumDustTypes.getByMeta(EnumDustTypes.java:38)
	at xilef11.mc.runesofwizardry_classics.items.ClassicDusts.getPrimaryColor(ClassicDusts.java:35)
	at com.zpig333.runesofwizardry.block.DustStorageBlockColor.func_186720_a(DustStorageBlockColor.java:28)
	at net.minecraft.client.renderer.color.BlockColors.func_189991_a(BlockColors.java:173)
	at buildcraft.transport.client.FacadeItemColours.func_186726_a(FacadeItemColours.java:20)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:148)
	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:339)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:162)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:134)
	at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:61)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:30)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:162)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:90)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:199)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:74)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3546_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:615)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:636)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1454)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Xilef11** [comment]
Thanks for the report. Do you have any more info about when it happens? (every time on login, or when doing something specific?)
It also looks like it's something related to JEI, so please list versions of RunesOfWizardry, the Classic Dusts Pack, JEI and Forge.
Also, please note that it could be a few weeks before I have time to look at this.

**Comment by liquidblur** [comment]
Most recent versions of JEI, Runes, and Classic. Forge 2624. Happened the first time when i pressed E than happened the second go around when i pressed E than maximized the screen.

**Comment by collwee** [comment]
happen to me also. it happen when going trough page.
seam to happen when going trough the page where buildcraft facade are in jei.

buildcraft 7.99.15 lastest jei whit forge 2613

i think there a problem whit your block in facade form

**Comment by Xilef11** [comment]
Not just JEI, also in creative menu. only for the classic dust blocks.
