### ISSUE TITLE
Animus 2.0.2 conflict

### ISSUE THREAD

**Issue by charlescannon** [Xilef11/Runes-of-Wizardry#47]
Adding animus causes runes of wizardry (1.8.8 and 1.8.9) to throw 

Caused by: java.lang.NoClassDefFoundError: com/zpig333/runesofwizardry/item/ItemInscriptionBauble
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more

and possibly related  (below) is thrown.

Caused by: java.lang.NoClassDefFoundError: baubles/api/IBauble
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

**Comment by Xilef11** [comment]
Hi,  
The 1.8 versions are a bit flaky as modding was in a mess back then.  
Do you have Baubles installed? which version?  
Does animus add anything related to Baubles?  
Please link the whole log/crash report via pastebin or gist.github.com

**Comment by charlescannon** [comment]
I checked with Animus they report doing nothing with either mod and I have baubles installed

https://pastebin.com/C5SAp0Me

**Comment by TeamDman** [comment]
Animus author here, reproducing the bug with just Animus (and its dependencies), Baubles, and Runes of Wizardry installed. Removing Animus (but leaving the dependencies) resolves the crash somehow.
![image](https://user-images.githubusercontent.com/9356891/41992618-fc430ef0-7a16-11e8-8023-5e4a307b1c8e.png)
Crash log:
https://pastebin.com/jZMGBw9E

Related files:
https://github.com/Xilef11/Runes-of-Wizardry/blob/master/src/main/java/com/zpig333/runesofwizardry/item/ItemInscriptionBauble.java

The entire stacktrace comes from your mod, but somehow the crash only happens if Animus is installed. Not too sure what we can do on our end to help.

**Comment by Xilef11** [comment]
Hi,  
From the crash reports, I believe it's an issue with the load order (attempting to construct runesofwizardry before Baubles), if that's the case it should be an easy fix on my side (i.e. I forgot to add Baubles to the dependency string of RoW)

the strange thing is that it only happens if Animus is on. I guess that the combination of RoW trying to load before Guide-API while Animus wants to load after Blood Magic and GuideAPI somehow kicks Baubles to the end of the list, causing the crash.

**Comment by Xilef11** [comment]
Should be fixed in v1.12.2-0.8.10 (will be on Curse in a few minutes)
